# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cogito_servicer/cogito.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cogito_servicer/cogito.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x63ogito_servicer/cogito.proto\x12\x06\x63ogito\"C\n\x08Question\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x17\n\x0f\x63onversation_id\x18\x02 \x01(\t\x12\r\n\x05\x61gent\x18\x03 \x01(\t\"\x19\n\x06\x41nswer\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t21\n\x06\x43ogito\x12\'\n\x03\x41sk\x12\x10.cogito.Question\x1a\x0e.cogito.Answerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cogito_servicer.cogito_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUESTION']._serialized_start=40
  _globals['_QUESTION']._serialized_end=107
  _globals['_ANSWER']._serialized_start=109
  _globals['_ANSWER']._serialized_end=134
  _globals['_COGITO']._serialized_start=136
  _globals['_COGITO']._serialized_end=185
# @@protoc_insertion_point(module_scope)
