# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cogito.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cogito.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ogito.proto\x12\x06\x63ogito\"(\n\x07Message\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"6\n\x11\x43ompletionRequest\x12!\n\x08messages\x18\x01 \x03(\x0b\x32\x0f.cogito.Message\"&\n\x12\x43ompletionResponse\x12\x10\n\x08response\x18\x01 \x01(\t2T\n\rCogitoService\x12\x43\n\nCompletion\x12\x19.cogito.CompletionRequest\x1a\x1a.cogito.CompletionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cogito_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE']._serialized_start=24
  _globals['_MESSAGE']._serialized_end=64
  _globals['_COMPLETIONREQUEST']._serialized_start=66
  _globals['_COMPLETIONREQUEST']._serialized_end=120
  _globals['_COMPLETIONRESPONSE']._serialized_start=122
  _globals['_COMPLETIONRESPONSE']._serialized_end=160
  _globals['_COGITOSERVICE']._serialized_start=162
  _globals['_COGITOSERVICE']._serialized_end=246
# @@protoc_insertion_point(module_scope)
