from rich import box
from rich.markdown import TableElement
from rich.table import Table


def patch_markdown_tables() -> None:
    """Patch Rich's Markdown TableElement to use a more compact table style. Generated by GPT-5.1 & verified by Will C."""

    if getattr(TableElement, "_cogito_patched", False):
        return

    def _rich_console(self, console, options):
        table = Table(
            box=box.SIMPLE,
            pad_edge=False,
            padding=(1, 2),
            style="markdown.table.border",
            show_edge=True,
            collapse_padding=True,
        )

        if self.header is not None and self.header.row is not None:
            for column in self.header.row.cells:
                heading = column.content.copy()
                heading.stylize("markdown.table.header")
                table.add_column(heading)

        if self.body is not None:
            for row in self.body.rows:
                row_content = [element.content for element in row.cells]
                table.add_row(*row_content)

        yield table

    TableElement.__rich_console__ = _rich_console
    TableElement._cogito_patched = True
